### ISSUE TITLE
Сеты и атрибуты

### ISSUE THREAD

**Issue by loveorigami** [NullRefExcep/yii2-eav#5]
Начал работать с модулем. 
Возникло пару вопросов и замечаний ).

1.. Модель связывается с EAV посредством сетов. Сеты в свою очередь завязаны на атрибуте.
https://github.com/NullRefExcep/yii2-eav/blob/master/src/migrations/m170520_151321_eav__create_tables.php#L26 
Т.е. один атрибут может быть в одном сете. Что не очень удобно.

Например, атрибут ```color -> option -> [red, blue, green]``` входит в сет Phones. Если мне нужно цвета привязять к другой модели (Dresses, Flowers, Papers...), мне нужно будет для каждого из них заново заводить атрибут color и вводить в него те же самые опции.
И при поиске в гриде вылезят ошибки, когда я буду искать по 'color' в разных моделях. Т.е. условно, показать все синие телефоны, цветы и бумагу...

То есть, напрашивается связь в обратную сторону. Атрибуты не зависят от сета. Сет зависит от атрибутов. Один атрибут может входить в несколько сетов.

2. Не уникальное хранение данных
```
            $this->createTable('{{%eav_entity_value_int}}', [
                'id' => $this->primaryKey(),
                'attribute_id' => $this->integer(),
                'entity_id' => $this->integer(),
                'value' => $this->integer(),
            ]);
```
Пара 'attribute_id' + entity_id - не уникальна.

Даже сейчас, в текущей структуре, допустим, я создам сет Meta. В нем будут атрибуты title, description, keywords.

У меня есть несколько моделей (Pages, News, Articles...), к которым я хочу его применить.
Заполнив его в Pages для id = 1, и перейдя к редактированию News c id=1, я получу данные из Pages.

Т.е. хранение данных должно быть примерно таким
```
            $this->createTable('{{%eav_entity_value_int}}', [
                'id' => $this->primaryKey(),
                'attribute_id' => $this->integer(),
                'entity_id' => $this->integer(),
                'entity_class' => $this->string(), // Pages::class, News::class,  etc.
                'value' => $this->integer(),
            ]);
```

3. В методе attach в поведении
```php
public function behaviors()
{
    return [
        /** ... **/
        'eav' => [
            'class' => Entity::class,
            'entity' => function () {
                return new EntityModel([
                    'sets' => [
                        Set::findOne(['code' => 'product']), //product -- set from db
                    ],
                ]);
            },
        ],
    ];
}
```
Запускается поиск сета. Это нормально, если модель одна.
Если делать поиск в гриде по одному атрибуту (color), то этот запрос
```Set::findOne(['code' => 'product']), //product -- set from db``` выполняется для каждой строки грида.
Итого получаю 50 абсолютно одинаковых запросов на одной странице с гридом в 50 строк. Как от этого избавится, я пока сам не могу понять ). 

Как только убираю анонимку - выскакивают ошибки об отсутствующих атрибутах у основной модели (Pages, News...). 

Как я понял, этот запрос нужен, чтобы получить атрибуты у связанной модели и сделать их безопасными 

https://github.com/NullRefExcep/yii2-eav/blob/master/src/behaviors/Entity.php#L103

сами же данные для строк в гриде вытягиваются через связи и потом заполняются в эти приаттаченые атрибуты... Т.е еще раз вытягивать сет для каждой строки нет необходимости.

**Comment by loveorigami** [comment]
Это пригодится
https://yiiframework.ru/forum/viewtopic.php?f=19&t=47197

Вот почему у меня, как убираю анонимку, нет eav атрибутов. Нужно будет попробовать переписать через init()

**Comment by ZAYEC77** [comment]
Касательно уникальных атрибутов -- делайте отдельные сеты.
Думаю, это рабочее решение.

Дублирование полей не будет, если использовать один атрибут к одной модели.
На практике я не встречал случаев, когда один и тот же аттрибут нужно было держать для разных моделей.
Если вам нужна связь m-m для сетов и аттрибутов, можно попробовать реализовать.
Приведите, пожалуйста, реальный пример. Пример с Dresses, Flowers, Papers -- не рабочий, так как это могут быть объект одной таблицы, например products. 
Именно для этого и создан модуль, чтобы не плодить таблицы, а добавить аттрибут только для части объектов.

Если у вас уже разные таблицы -- зачем вам eav? -- делайте поля в таблице)

Проблема с N к-вом запросов решаеться использованием кеша или [мемоизации](https://github.com/NullRefExcep/yii2-useful/blob/master/src/helpers/Memoize.php)
Вопрос об анонимке не понял.

**Comment by loveorigami** [comment]
Я рассматриваю каталог, как тут #2 

> Дублирование полей не будет, если использовать один атрибут к одной модели.
На практике я не встричал случаев, когда один и тот же аттрибут нужно было держать для разных моделей.

Берем атрибут color. Прописываем его опции (красный. зеленый. желтый)...
Теперь рабочий пример из реального магазина.
Есть категория "Кондиционеры" https://comfy.ua/conditioner-split/. Для него создаю сет "conditioner-split" с набором всех атрибутов для кондиционеров, включая атрибут color.

![001](https://user-images.githubusercontent.com/98164/40885499-0ec30570-6730-11e8-96fd-8738260f1946.png)

В другой категории - https://comfy.ua/smartfon/ также есть атрибут 'color' 

![002](https://user-images.githubusercontent.com/98164/40885576-aa3d1fa8-6731-11e8-845d-0af627fc244b.png)

В телевизорах https://comfy.ua/flat-tvs/
![003](https://user-images.githubusercontent.com/98164/40885588-d1d36a40-6731-11e8-9e62-c084cd9bc0c4.png)

И т.д....

Т.е получается, под каждую такую категорию, я должен создавать атрибут color и по новой вбивать все цвета.

По количеству запросов в гриде - я сделаю отдельное issue, чтоб более предметно обсудить этот вопрос.

**Comment by ZAYEC77** [comment]
Спасибо за ответ.

Ваш пример понятен.
Следующий вопрос в том, критичен ли вам этот оверхед (когда нужно будет дублировать поля) или это просто желание иметь супер нормализованную схему). К тому же, как я вижу из примера цвета в каждом атрибуте не всегда одинаковые.

Изменения, о которых вы пишите: 
1. ломают существующую структуру БД и нужно будет сделать какой-то скрипт для миграции.
2. добавляют еще один запрос или усложняют существующий (нужно сходить в +1 таблицу).
3. добавляют сложность в код (потенциальные места для багов).

Еще как вараинт можем обсудить реализацию связи м-м на уровне атрибут-значение.
Возможно тоже будет хорошим решением.

**Comment by loveorigami** [comment]
> Следующий вопрос в том, критичен ли вам этот оверхед (когда нужно будет дублировать поля) или это просто желание иметь супер нормализованную схему). К тому же, как я вижу из примера цвета в каждом атрибуте не всегда одинаковые.

Критичен до той поры, если я хочу в гриде с товарами вывести фильтр по цвету. Т.к. у меня их будет несколько, соответственно, этого я сделать не смогу. 

Что касается - разных цветов, то это могут быть и разные атрибуты (как у Вас), а возможно - это виджет, который выводит только те цвета, которые имеют связи с товарами из данной категории. 

Я такое делал тут
https://www.gintur.com/all. В фильтре слева показываются только те города, у которых есть хотя бы один объект. 

> ломают существующую структуру БД и нужно будет сделать какой-то скрипт для миграции.
Я не призываю переписывать модуль, просто поделился идеями, с которыми уже сталкивался в своей практике. И ваш модуль показался наиболее подходящим из тех, что уже есть на github-e

Можно сделать отдельную ветку, и в ней попробовать сделать связь m-m для атрибутов.

**Comment by ZAYEC77** [comment]
хорошо, договорились
не могу вам гарантировать сроки реализаци, если у вас есть желание, можете попробовать реализовать этот функционал самостоятельно, буду рад PR)

**Comment by ZAYEC77** [comment]
@loveorigami 
Подскажите, вас устроит вариант когда одни и те же опции можно будет додавлять к нескольким аттрибутам?
Такой вариант мне кажеться менее затратным по ресурсам БД.
Нужно будет связать атрибуты с опциями через отдельную таблицу.
А если делать m-m связь на уровне сет - аттрибут, тогда кроме m-m таблицы нужно нужно будет во все таблицы со значениями (`eav_entity_value_*`) добавлять колонку set_id.
Так как значений на порядок больше, чем опций, такое решение кажеться мне более приемлемым.

**Comment by loveorigami** [comment]
Постараюсь объяснить, чего я хочу добиться.
1. У меня есть каталог, в котором к разной категории привязан разный сет
Условно
```php
            'entity' => function () {
                if ($this->model->cat_id == 2) {
                    return new Entity([
                        'sets' => Memoize::call([Set::class, 'findAll'], [['slug' => 'demo2']]),
                    ]);
                }
                return new Entity([
                    'sets' => Memoize::call([Set::class, 'findAll'], [['slug' => 'demo1']]),
                ]);
            },
```
это работает.


2. У большинства продуктов есть атрибут (color), который мне необходимо вывести в гриде. Сейчас, если я привяжу его в одном сете (demo1), и не привяжу в другом (demo2) - появляется ошибка о неизвестном атрибуте.  
Ок. Я создаю еще один атрибут с таким же кодом (color)

![001](https://user-images.githubusercontent.com/98164/41158963-8944f522-6b33-11e8-9f74-c27dfb1bce18.jpg)

3. Немного поправил ваш пример, чтобы в грид выводить только указанный атрибут из массива eavAttributes.

```php
        foreach ($entity->getAttributesConfig() as $code => $item) {
            if (in_array($code, $this->eavAttributes)) {
                $column = [
                    'label' => $item['name'],
                    'attribute' => $code,
                ];
                //$column = self::addFilter($column, $item, $searchModel);
                // $column = self::addValue($column, $item);
                $result[] = $column;
            }
        }
```

 Заполняю данные. 111 - для demo1 и 222 - для demo2

Результат
![002](https://user-images.githubusercontent.com/98164/41159244-862619c4-6b34-11e8-8f3d-c6232e757e4b.jpg)

**Comment by loveorigami** [comment]
4. Делаю фильтрацию
Для 111 - работает

![003](https://user-images.githubusercontent.com/98164/41159314-cc8fcf0e-6b34-11e8-92bf-4e5cdf139121.jpg)

для 222 - нет

![004](https://user-images.githubusercontent.com/98164/41159348-ea396ec0-6b34-11e8-880e-d1873b4484f2.jpg)

Оно и понятно. Т.к. в Search модели поиск идет по первому попавшемуся атрибуту color.

Вот исходя из этого следует, что 

1. Атрибут, если делать по нему затем поиск, должен быть уникальным.
2. Чтоб не было ошибок для записей с непривязанным поисковым атрибутом (color), получение safe валидаторов можно вынести в отдельный трейт. И подключить его в Search модели. Передать в эту модель название eav атрибута.

В самой Search модели вытащить все данные leftJoin по этому атрибуту.

**Comment by ZAYEC77** [comment]
а почему вы не можете создать сет со всеми общими атрибутами?
тогда у вас будет один color для всех товаром (если вам так нужно).

**Comment by ZAYEC77** [comment]
А если у вас по факту должны быть два атрибута (base_color и border_color)  тогда, это два разных атрибута и ни в коем случае не один.
В таком случае вам нужен фильтр по категориям (например выше грида) и уже по результатами отборки по категории выводить нужные колонки в гриде.

**Comment by loveorigami** [comment]
Это идея. Попробую с общими параметрами. Отпишусь.

**Comment by ZAYEC77** [comment]
Товарам у которых вообще не может быть цвета либо не добавляйте сет с цветом, либо сделайте отдельное значение ("не указан" или что-то в этом духе).

**Comment by loveorigami** [comment]
В этом и загвоздка. Если не будет такого аттрибута, в гриде получу ошибку. См, выше

**Comment by loveorigami** [comment]
Пока на данный момент так устраивает с сетом "для всех" записей

```php
            'entity' => function () {
                return new Entity([
                    'sets' => Memoize::call(
                        [Set::class, 'findAll'], [['slug' => ['all', 'demo' . $model->cat_id],]]
                    ),
                ]);
            },
```
Так я получаю при создании модели все общие атрибуты. а при редактировании + из сета demo1, .... demoN

Любой общий атрибут я могу использовать в гриде.
