### ISSUE TITLE
Много запросов в гриде

### ISSUE THREAD

**Issue by loveorigami** [NullRefExcep/yii2-eav#7]
После того, как привязал Eav к модели, независимо от того, вывожу я Eav-аттрибуты в гриде или нет, все равно идут однотипные запросы.

Сейчас у в гриде 4 записи => получаю 5 одинаковых запросов

![2018-06-05_12-34-44](https://user-images.githubusercontent.com/98164/40967905-f689ef12-68bc-11e8-86b2-d9c1e13e7a5d.jpg)

**Comment by ZAYEC77** [comment]
проблема в коде привязки поведения (метод behaviors() вашей модели)
попробуйте добавить кэш или мемоизацию

**Comment by loveorigami** [comment]
Код, как в доке
```php
public function behaviors()
{
    return [
        /** ... **/
        'eav' => [
            'class' => Entity::class,
            'entity' => function () {
                return new EntityModel([
                    'sets' => [
                        Set::findOne(['code' => 'product']), //product -- set from db
                    ],
                ]);
            },
        ],
    ];
}
```

У вас должно быть тоже самое. Посмотрите в дебаг панель в гриде, где есть привязка EAV модуля.

Вот про эту анонимку я имел ввиду в предыдущем issue

**Comment by ZAYEC77** [comment]
В документации код для примера, нужно понимать, что метод behaviors вызывается для каждого екземпляра модели.

Сделайте вместо:

```php
Set::findOne(['code' => 'product']),
``` 

```php
\nullref\useful\helpers\Memoize::call([Set::class, 'findOne'],[['code' => 'product']]),
```

**Comment by loveorigami** [comment]
А так пропадают eav аттрибуты в гриде.
Я так понимаю, этот запрос дергает для каждого owner-a (строки в гриде) список eav-аттрибутов. 
Затем по ним получает ValueModel и далее возвращает join-ы для связи с основной моделью.

**Comment by ZAYEC77** [comment]
в каком метода вы это сделали?

**Comment by loveorigami** [comment]
В поведении

```php
            'entity' => function () {
                return new Entity([
                    'sets' => Memoize::call([Set::class, 'findAll'], ['slug' => ['demo']]), // не работает
                    //'sets' => Set::findAll(['slug' => ['demo']]), // работает
                ]);
            },
```

**Comment by ZAYEC77** [comment]
думаю, проблема в скобках, нужно:
```php
'sets' => Memoize::call([Set::class, 'findAll'], [['slug' => ['demo']]])
```

**Comment by loveorigami** [comment]
Точно! Спасибо!
